symbols:
  - BTCUSDT
  - ETHUSDT
  - ADAUSDT
  - DOTUSDT
  - LINKUSDT

server:
  port: 8080
  host: "0.0.0.0"

database:
  path: "./price_tracker.db"

ohlc_periods:
  - "10s"
  - "30s"
  - "1m"
  - "2m"
  - "5m" 